steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hackquest-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hackquest-backend:latest'
      - './backend'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/hackquest-backend'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hackquest-backend'
      - '--image=gcr.io/$PROJECT_ID/hackquest-backend:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=80'
      - '--set-env-vars=NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/hackquest-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/hackquest-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
